In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [4]:
np.arange(-1,-10,-2)

array([-1, -3, -5, -7, -9])

In [5]:
np.arange(0.5,3,1)

array([0.5, 1.5, 2.5])

In [6]:
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [7]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [10]:
np.linspace(1,20,5,retstep=True)

(array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]), 4.75)

In [11]:
np.linspace(1,20,5,endpoint=False)

array([ 1. ,  4.8,  8.6, 12.4, 16.2])

In [12]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros(7).dtype

dtype('float64')

In [15]:
np.zeros(7,dtype=int).dtype

dtype('int32')

In [16]:
np.full(5,10.5)

array([10.5, 10.5, 10.5, 10.5, 10.5])

In [17]:
np.empty(5)

array([10.5, 10.5, 10.5, 10.5, 10.5])

In [18]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.empty((2,3),dtype=int)

array([[         0, 1071644672,          0],
       [1073217536,          0, 1074003968]])

In [20]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.identity((3,5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [22]:
np.eye(3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.meshgrid([0,1,2,3])

In [24]:
a_1 = np.array([[5,5,5],
                [5,5,5]])
a_2 = np.array([[10,10,10],
                [10,10,10]])

In [25]:
np.concatenate([a_1,a_2])

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [10, 10, 10],
       [10, 10, 10]])

In [26]:
np.concatenate([a_1,a_2],axis=1)

array([[ 5,  5,  5, 10, 10, 10],
       [ 5,  5,  5, 10, 10, 10]])

In [27]:
np.hstack((a_1,a_2))

array([[ 5,  5,  5, 10, 10, 10],
       [ 5,  5,  5, 10, 10, 10]])

In [30]:
a_1 = np.array([2,8,5])
a_2 = np.array([[40,20,70],
               [90,10,60],
               [80,30,50]])

In [31]:
np.hstack((a_1,a_2))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [32]:
a_1 = np.array([[3,6,2,5],
               [4,1,7,5],
               [3,5,8,5]])
a_2 = np.array([[40,20,70],
               [90,10,60],
               [80,30,50]])

In [33]:
np.hstack((a_1,a_2))

array([[ 3,  6,  2,  5, 40, 20, 70],
       [ 4,  1,  7,  5, 90, 10, 60],
       [ 3,  5,  8,  5, 80, 30, 50]])

In [35]:
a_1 = np.array([[3,6,2,5],
               [4,1,7,5],
               [3,5,8,5]])
a_2 = np.array([[40,20,70,2],
               [90,10,60,1],
               [80,30,50,5]])

In [36]:
np.vstack((a_1,a_2))

array([[ 3,  6,  2,  5],
       [ 4,  1,  7,  5],
       [ 3,  5,  8,  5],
       [40, 20, 70,  2],
       [90, 10, 60,  1],
       [80, 30, 50,  5]])

In [37]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [38]:
np.stack([a,a])

array([[1, 2, 3],
       [1, 2, 3]])

In [39]:
b = np.array([[1,2,3],[4,5,6]])

In [40]:
np.stack([b,b])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [41]:
a = np.array([[1,2],[3,4]])

In [42]:
np.block([a,a])

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [43]:
np.block([[a],[a]])

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [45]:
np.block([[[a]],[[a]]])

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [46]:
np.block([[a,a],[a,a]])

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [47]:
a = np.array([1,2,3])

In [48]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [52]:
b = np.array([[1,2],[3,4]])

In [55]:
np.repeat(b,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [56]:
np.repeat(b,2,axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [58]:
np.repeat(b,3,axis = 1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [61]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [62]:
np.tile(a,(2,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [63]:
np.tile(a,(2,2,2))

array([[[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]],

       [[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]]])

In [68]:
a = np.array([1,5,12,0,5,1])

In [69]:
np.reshape(a,(2,3))

array([[ 1,  5, 12],
       [ 0,  5,  1]])

In [70]:
np.reshape(a,(3,1,2))

array([[[ 1,  5]],

       [[12,  0]],

       [[ 5,  1]]])

In [71]:
np.reshape(a,(2,-1))

array([[ 1,  5, 12],
       [ 0,  5,  1]])

In [78]:
a_1 = np.transpose([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [79]:
a_1

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [76]:
np.transpose(a_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a_2 = np.array([[[1,2,3,4]],
             [[5,6,7,8]],
             [[9,10,11,12]]])

In [84]:
np.transpose(a_2,(0,1,2))

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [85]:
a_2.shape

(3, 1, 4)

In [86]:
np.transpose(a_2,(2,1,0))

array([[[ 1,  5,  9]],

       [[ 2,  6, 10]],

       [[ 3,  7, 11]],

       [[ 4,  8, 12]]])

In [87]:
np.transpose(a_2,(0,2,1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [88]:
np.transpose(a_2,(0,2,1)).shape

(3, 4, 1)

In [90]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [91]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a.flatten(order = 'F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [94]:
b = a.flatten()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [96]:
np.clip(a,2,5)

array([2, 2, 3, 4, 5, 5])

In [97]:
np.clip(a,2,None)

array([2, 2, 3, 4, 5, 6])

In [98]:
np.clip(a,2,5,out=a)

array([2, 2, 3, 4, 5, 5])

In [99]:
a

array([2, 2, 3, 4, 5, 5])

In [100]:
a = np.array([20,30,50,60,10,40])
a

array([20, 30, 50, 60, 10, 40])

In [101]:
np.sort(a)

array([10, 20, 30, 40, 50, 60])

In [102]:
np.argsort(a)

array([4, 0, 1, 5, 2, 3], dtype=int64)

In [103]:
b = np.array([[10,2,30,4],[1,20,3,40]])

In [104]:
np.sort(b,axis=0)

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [105]:
np.sort(b,axis=1)

array([[ 2,  4, 10, 30],
       [ 1,  3, 20, 40]])

In [106]:
np.sort(b,axis=None)

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [108]:
np.random.seed(0)
a = np.random.randint(0,11,size=50)
a

array([ 5,  0,  3,  3,  7,  9,  3,  5,  2,  4,  7,  6,  8,  8, 10,  1,  6,
        7,  7,  8,  1,  5,  9,  8,  9,  4,  3,  0,  3,  5,  0,  2,  3,  8,
        1,  3,  3,  3,  7,  0,  1,  9,  9,  0, 10,  4,  7,  3,  2,  7])

In [109]:
np.histogram(a)

(array([ 5,  4,  3, 10,  3,  4,  2,  7,  5,  7], dtype=int64),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [110]:
np.histogram(a,bins=5)

(array([ 9, 13,  7,  9, 12], dtype=int64),
 array([ 0.,  2.,  4.,  6.,  8., 10.]))

In [111]:
np.histogram(a,density=True)

(array([0.1 , 0.08, 0.06, 0.2 , 0.06, 0.08, 0.04, 0.14, 0.1 , 0.14]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [112]:
a_1 = np.array([1,2,3,4,5])

In [113]:
np.append(a_1,100)

array([  1,   2,   3,   4,   5, 100])

In [118]:
np.append(a_1,[50,55,60])

array([ 1,  2,  3,  4,  5, 50, 55, 60])

In [119]:
a_2 = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [122]:
b = np.array([[10,20,30]])

In [123]:
np.append(a_2,b,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [124]:
c = np.array([[10],[20],[30]])

In [125]:
np.append(a_2,c,axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [126]:
a = np.array([1,5,12,0,5,1])

In [127]:
np.put(a,1,500)
a

array([  1, 500,  12,   0,   5,   1])

In [128]:
np.put(a,[0,1,2],[10,20,30])
a

array([10, 20, 30,  0,  5,  1])

In [129]:
np.put(a,15,200)
a

IndexError: index 15 is out of bounds for axis 0 with size 6

In [130]:
np.put(a,6,500,mode='wrap')
a

array([500,  20,  30,   0,   5,   1])

In [131]:
np.put(a,6,500,mode='clip')
a

array([500,  20,  30,   0,   5, 500])

In [132]:
a_1 = np.array([1,5,2,6,8,3,4])

In [133]:
np.putmask(a_1,a_1 >=5 , 100)
a_1

array([  1, 100,   2, 100, 100,   3,   4])

In [134]:
a_2 = np.array([[1,7,5],
               [4,3,8],
               [12,2,1]])

In [135]:
np.putmask(a_2,a_2 >=5 , 100)
a_2

array([[  1, 100, 100],
       [  4,   3, 100],
       [100,   2,   1]])

In [136]:
np.putmask(a_2,a_2 >=5 , [100,10])
a_2

array([[  1,  10, 100],
       [  4,   3,  10],
       [100,   2,   1]])

In [137]:
a = np.array([1,5,12,0,5,1])

In [139]:
np.mean(a)

4.0

In [141]:
a_2 = np.reshape(a,(2,3))

In [144]:
np.mean(a_2,axis=1)

array([6., 2.])

In [145]:
np.mean(a_2,axis=0)

array([0.5, 5. , 6.5])

In [146]:
np.nanmean(a_2,axis=0)

array([0.5, 5. , 6.5])

In [147]:
np.average(a)

4.0

In [148]:
w = np.array([0.4,0.2,0.1,
              0.5,0.2,0.4])

In [149]:
np.average(a,weights = w)

2.222222222222222

In [151]:
np.median(a)

3.0

In [152]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [153]:
np.median(a)

4.5

In [154]:
np.median(a,axis=0)

array([3., 4., 5., 6.])

In [155]:
np.median(a,axis=1)

array([2.5, 6.5])

In [156]:
b = np.array([1,np.nan,3,4])
b

array([ 1., nan,  3.,  4.])

In [157]:
np.median(b)

nan

In [158]:
np.nanmedian(b)

3.0

In [159]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [160]:
np.sum(a)

36

In [161]:
np.sum(a,axis=0)

array([ 6,  8, 10, 12])

In [162]:
np.sum(a,axis=1)

array([10, 26])

In [163]:
np.var(a)

5.25

In [164]:
np.std(a)

2.29128784747792

In [165]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [166]:
a.max()

9

In [167]:
a.min()

1

In [168]:
a.max(axis=0)

array([7, 8, 9])

In [169]:
a.max(axis=1)

array([3, 6, 9])

In [170]:
a.min(axis=1)

array([1, 4, 7])

In [171]:
np.amax(a)

9

In [173]:
np.amin(a)

1

In [174]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,np.nan]])

In [175]:
np.max(a)

nan

In [176]:
np.nanmax(a)

8.0

In [177]:
np.nanmax(a,axis=0)

array([7., 8., 6.])

In [178]:
np.nanmin(a,axis=0)

array([1., 2., 3.])

In [179]:
a_1 = np.array([10,23,53,33,42,19])

In [181]:
np.argmax(a_1)

3

In [182]:
np.argmin(a_1)

0

In [183]:
a_2 = np.array([10,10,53,33,53,19])

In [184]:
np.argmax(a_2)

2

In [185]:
np.argmin(a_2)

0

In [187]:
a_4 = np.array([[10,32,22,19,29],
              [22,59,18,53,27]])

In [192]:
np.argmin(a_4 ,axis=1)

array([0, 2], dtype=int64)

In [193]:
a = np.array([-2,5,-8,-1,-3])
np.abs(a)

array([2, 5, 8, 1, 3])

In [194]:
a = np.array([-2.7,1.9,-3,4])
np.abs(a)

array([2.7, 1.9, 3. , 4. ])

In [201]:
a_1 = np.array([2,5,9])
a_2 = np.array([3,1,7])

In [196]:
np.maximum(a_1,a_2)

array([3, 5, 9])

In [197]:
a_3 =np.array([5,np.nan,3])

In [198]:
np.maximum(a_1,a_3)

array([ 5., nan,  9.])

In [199]:
np.fmax(a_1,a_3)

array([5., 5., 9.])

In [200]:
np.minimum(a_1,a_3)

array([ 2., nan,  3.])

In [202]:
np.add(a_1,a_2)

array([ 5,  6, 16])

In [203]:
np.subtract(a_1,a_2)

array([-1,  4,  2])

In [204]:
np.multiply(a_1,a_2)

array([ 6,  5, 63])

In [209]:
np.divide(a_1,a_2)

array([0.66666667, 5.        , 1.28571429])

In [210]:
a = np.array([[150,160,170,180,190],
             [55,60,65,60,70]])

In [211]:
np.corrcoef(a)

array([[1.        , 0.83205029],
       [0.83205029, 1.        ]])

In [213]:
b = np.array([60,85,55,60,70])
np.corrcoef(a,b)

array([[ 1.        ,  0.83205029, -0.06622662],
       [ 0.83205029,  1.        ,  0.05510388],
       [-0.06622662,  0.05510388,  1.        ]])

In [214]:
np.cov(a)

array([[250. ,  75. ],
       [ 75. ,  32.5]])

In [215]:
b = np.array([60,85,55,60,70])
np.cov(a,b)

array([[250.  ,  75.  , -12.5 ],
       [ 75.  ,  32.5 ,   3.75],
       [-12.5 ,   3.75, 142.5 ]])

In [216]:
np.cov(a,b,bias = True)

array([[200.,  60., -10.],
       [ 60.,  26.,   3.],
       [-10.,   3., 114.]])

In [217]:
a = np.array([[1,7,1,3,1],
             [0,1,0,3,1],
             [3,8,0,6,1]])

In [218]:
np.all(a)

False

In [219]:
np.all(a,axis=0)

array([False,  True, False,  True,  True])

In [220]:
np.all(a,axis=1)

array([ True, False, False])

In [221]:
np.all(a<5)

False

In [222]:
np.all(a<5,axis=0)

array([ True, False,  True, False,  True])

In [223]:
np.any(a<5)

True

In [226]:
a = np.array([[[1,2,3],[4,5,6]],
             [[1,2,3],[4,5,6]]])

In [227]:
np.save("test",a)

In [230]:
np.load("test.npy")

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [231]:
np.savez("test1",a,a)

In [232]:
np.load("test1.npz").files

['arr_0', 'arr_1']

In [233]:
np.load("test1.npz")["arr_0"]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [234]:
a = np.random.randn(2,3)

In [235]:
np.savetxt("test.csv",a)

In [236]:
np.savetxt("test.csv",a,fmt="%.2f")

In [237]:
np.loadtxt("test.csv")

array([[-0.44, -0.35, -0.88],
       [-0.44, -0.54, -1.32]])